server:
  port: 8001


spring:
  application:
    name: cloud-payment-hystrix-service


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: paymentHystrix8001
    prefer-ip-address: true   #网页eureka访问路径，可现实Ip地址