server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true    #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh   #路由的ID，没有固定规律但要求唯一，建议配合服务名
          #断言匹配成功后提供服务的路由地址 （转发路由地址为http://localhost:8001/cloudTest/searceData/**）,存在问题，地址写死不能实现负载均衡
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service         #lb代表负载均衡（动态路由）
          predicates:
            - Path=/cloudTest/searceData/**   #断言，路径相匹配的进行路由（与8001的controller路径进行匹配）
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/cloudTest/payment/getLB/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/