server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/
      #defaultZone: http://eureka7001.com:7001/eureka/
  #server:
    #enable-selfpreservation: false   #关闭自我保护机制
    #eviction-interval-timer-in-ms: 2000   #eureka服务端接收到客户端最后一次心跳后到剔除服务的时间间隔
