

#设置feign 客
server:
  port: 80
spring:
  application:
    name: cloud-order-feign-service
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: consumerFeign80
    prefer-ip-address: true   #网页eureka访问路径，可现实Ip地址户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#OpenFeign日志增强配置
logging:
  level:
    com.zn.springCloud.service.PaymentFeignService: DEBUG   #feign调用接口实现DEBUG日志打印

