server:
  port: 80


spring:
  application:
    name: cloud-order-feign-hystrix-service

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: consumerFeignHystrix80
    prefer-ip-address: true   #网页eureka访问路径，可现实Ip地址

#开启hystrix
feign:
  hystrix:
    enable: true


ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 6000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 6000